#include "insignia_attention.cuh"
#include <cuda_runtime.h>
namespace insignia {
// GQA decode for one query token against the contiguous KV cache. Token count is read from
// device memory (pos_dev[0] + base + 1) so the whole step is CUDA-graph replayable; the
// score buffer is a fixed 4096-slot array instead of dynamic shared memory for the same reason.
__global__ __launch_bounds__(256, 2) void gqa_decode_kernel(const float*__restrict__ q,const float*__restrict__ kc,const float*__restrict__ vc,float*__restrict__ out,const int*__restrict__ pos_dev,int base){const int head=blockIdx.x,tid=threadIdx.x,kvh=head>>2;const int tokens=__ldg(pos_dev)+base+1;__shared__ float score[4096];const float scale=.0625f;float mx=-3.402823466e+38F;for(int t=tid;t<tokens;t+=256){float z=0;for(int d=0;d<256;d++)z=fmaf(q[head*256+d],kc[(size_t(t)*4+kvh)*256+d],z);z*=scale;score[t]=z;mx=fmaxf(mx,z);}for(int m=16;m;m>>=1)mx=fmaxf(mx,__shfl_xor_sync(0xffffffff,mx,m));__shared__ float red[8],smx,sden;int lane=tid&31,warp=tid>>5;if(lane==0)red[warp]=mx;__syncthreads();if(warp==0){mx=lane<8?red[lane]:-3.402823466e+38F;for(int m=16;m;m>>=1)mx=fmaxf(mx,__shfl_xor_sync(0xffffffff,mx,m));if(lane==0)smx=mx;}__syncthreads();mx=smx;float den=0;for(int t=tid;t<tokens;t+=256){float e=__expf(score[t]-mx);score[t]=e;den+=e;}for(int m=16;m;m>>=1)den+=__shfl_xor_sync(0xffffffff,den,m);if(lane==0)red[warp]=den;__syncthreads();if(warp==0){den=lane<8?red[lane]:0;for(int m=16;m;m>>=1)den+=__shfl_xor_sync(0xffffffff,den,m);if(lane==0)sden=1.f/den;}__syncthreads();float z=0;for(int t=0;t<tokens;t++)z=fmaf(score[t]*sden,vc[(size_t(t)*4+kvh)*256+tid],z);out[head*256+tid]=z;}
void gqa_decode(const float*q,const float*k,const float*v,float*out,const int*pos_dev,int base,int max_context,cudaStream_t s){gqa_decode_kernel<<<16,256,0,s>>>(q,k,v,out,pos_dev,base);}
}
