#include "insignia_decode.hpp"
#include "insignia_qwen_kernels.cuh"
#include "insignia_ops.cuh"
#include "insignia_attention.cuh"
#include "insignia_layout.cuh"
#include <cuda_runtime.h>
#include <cstdio>
#include <vector>
static void dump(FILE*f,float*d,int n){std::vector<float>h(n);cudaMemcpy(h.data(),d,n*4,cudaMemcpyDeviceToHost);fwrite(h.data(),4,n,f);}
int wmain(int argc,wchar_t**argv){if(argc!=3)return 2;insignia::ModelFile m(argv[1]);insignia::Qwen35Weights w(m,2ull<<30);insignia::DecodeWorkspace x(16);w.embed(42,x.hidden);insignia::Qwen35Decode d(w,x);for(int l=0;l<3;l++)d.layer(l);FILE*f=_wfopen(argv[2],L"wb");dump(f,x.hidden,4096);auto mat=[&](const std::string&base,float*in,float*out){auto z=w.matrix(base);insignia::mxfp4_gemv_mlx((uint32_t*)z.weight.data,(uint8_t*)z.scales.data,in,out,z.rows,z.cols,2);w.release(base);};std::string p="language_model.model.layers.3",a=p+".self_attn";auto iw=w.storage().acquire(p+".input_layernorm.weight");insignia::rmsnorm_bf16(x.hidden,(uint16_t*)iw.data,x.norm,1,4096,false);w.storage().release(p+".input_layernorm.weight");dump(f,x.norm,4096);mat(a+".q_proj",x.norm,x.gate);insignia::split_q_gate(x.gate,x.qkv,x.attn_gate);mat(a+".k_proj",x.norm,x.key);mat(a+".v_proj",x.norm,x.value);dump(f,x.qkv,4096);dump(f,x.attn_gate,4096);dump(f,x.key,1024);dump(f,x.value,1024);auto qw=w.storage().acquire(a+".q_norm.weight"),kw=w.storage().acquire(a+".k_norm.weight");insignia::qwen35_qk_norm_rope_gate(x.qkv,x.key,(uint16_t*)qw.data,(uint16_t*)kw.data,x.attn_gate,0);dump(f,x.qkv,4096);dump(f,x.attn_gate,4096);dump(f,x.key,1024);insignia::store_kv(x.key,x.value,x.kv_keys,x.kv_values,0);insignia::gqa_decode(x.qkv,x.kv_keys,x.kv_values,x.core,1);dump(f,x.core,4096);insignia::expand_gate_heads(x.attn_gate,x.qkv);dump(f,x.qkv,4096);insignia::sigmoid_mul(x.core,x.qkv,4096);dump(f,x.core,4096);mat(a+".o_proj",x.core,x.down);dump(f,x.down,4096);insignia::residual_add(x.hidden,x.down,4096);dump(f,x.hidden,4096);auto post=w.storage().acquire(p+".post_attention_layernorm.weight");insignia::rmsnorm_bf16(x.hidden,(uint16_t*)post.data,x.norm,1,4096,false);dump(f,x.norm,4096);w.storage().release(p+".post_attention_layernorm.weight");mat(p+".mlp.gate_proj",x.norm,x.gate);mat(p+".mlp.up_proj",x.norm,x.up);dump(f,x.gate,12288);dump(f,x.up,12288);insignia::silu_mul(x.gate,x.up,x.gate,12288);mat(p+".mlp.down_proj",x.gate,x.down);dump(f,x.down,4096);insignia::residual_add(x.hidden,x.down,4096);dump(f,x.hidden,4096);fclose(f);return 0;}
