#include "insignia_ops.cuh"
#include <cuda_runtime.h>
#include <cuda_bf16.h>
namespace insignia {
template<bool ZERO_CENTERED,bool GATED> __global__ void rms_kernel(const float*__restrict__ x,const float*__restrict__ w,const float*__restrict__ gate,float*__restrict__ y,int cols,float eps){const int row=blockIdx.x;float ss=0;for(int i=threadIdx.x;i<cols;i+=blockDim.x){float v=x[row*cols+i];ss=fmaf(v,v,ss);}for(int m=16;m;m>>=1)ss+=__shfl_xor_sync(0xffffffff,ss,m);__shared__ float partial[8];int lane=threadIdx.x&31,warp=threadIdx.x>>5;if(lane==0)partial[warp]=ss;__syncthreads();if(warp==0){ss=lane<8?partial[lane]:0;for(int m=16;m;m>>=1)ss+=__shfl_xor_sync(0xffffffff,ss,m);if(lane==0)partial[0]=rsqrtf(ss/cols+eps);}__syncthreads();const float inv=partial[0];for(int i=threadIdx.x;i<cols;i+=blockDim.x){float z=x[row*cols+i]*inv*(ZERO_CENTERED?1.0f+w[i]:w[i]);if constexpr(GATED){float g=gate[row*cols+i];z*=g/(1.0f+__expf(-g));}y[row*cols+i]=z;}}
void rmsnorm_zero_centered(const float*x,const float*w,float*y,int rows,int cols,float eps,cudaStream_t s){rms_kernel<true,false><<<rows,256,0,s>>>(x,w,nullptr,y,cols,eps);}void rmsnorm_gated_silu(const float*x,const float*w,const float*g,float*y,int rows,int cols,float eps,cudaStream_t s){rms_kernel<false,true><<<rows,256,0,s>>>(x,w,g,y,cols,eps);}
__global__ void silu_mul_kernel(const float*g,const float*u,float*y,int n){for(int i=blockIdx.x*blockDim.x+threadIdx.x;i<n;i+=blockDim.x*gridDim.x){float x=g[i];y[i]=(x/(1+__expf(-x)))*u[i];}}void silu_mul(const float*g,const float*u,float*y,int n,cudaStream_t s){silu_mul_kernel<<<((n+255)/256<4096?(n+255)/256:4096),256,0,s>>>(g,u,y,n);}
__global__ void add_kernel(float*x,const float*d,int n){for(int i=blockIdx.x*blockDim.x+threadIdx.x;i<n;i+=blockDim.x*gridDim.x)x[i]+=d[i];}void residual_add(float*x,const float*d,int n,cudaStream_t s){add_kernel<<<((n+255)/256<256?(n+255)/256:256),256,0,s>>>(x,d,n);}
__global__ void qk_norm_rope(float*q,float*k,const uint16_t*qw,const uint16_t*kw,float*gate,const int*pos_dev,int off){const int head=blockIdx.x,tid=threadIdx.x;const bool isq=head<16;float*p=isq?q+head*256:k+(head-16)*256;const uint16_t*w=isq?qw:kw;float v=p[tid],ss=v*v;for(int m=16;m;m>>=1)ss+=__shfl_xor_sync(0xffffffff,ss,m);__shared__ float mem[64];__shared__ float nsc;int lane=tid&31,warp=tid>>5;if(lane==0)mem[warp]=ss;__syncthreads();if(warp==0){ss=lane<8?mem[lane]:0;for(int m=16;m;m>>=1)ss+=__shfl_xor_sync(0xffffffff,ss,m);if(lane==0)nsc=rsqrtf(ss/256+1e-6f);}__syncthreads();v*=nsc*__bfloat162float(*reinterpret_cast<const __nv_bfloat16*>(w+tid));const int pos=__ldg(pos_dev)+off;if(pos!=0&&tid<64)mem[tid]=v;__syncthreads();if(pos!=0&&tid<64){const int half=tid&31;const float inv=__powf(10000000.0f,-float(2*half)/64.0f),a=float(pos)*inv,c=__cosf(a),s=__sinf(a);const float other=mem[tid<32?tid+32:tid-32];v=v*c+(tid<32?-other:other)*s;}p[tid]=v;}
void qwen35_qk_norm_rope_gate(float*q,float*k,const uint16_t*qw,const uint16_t*kw,float*g,const int*pos_dev,int off,cudaStream_t s){qk_norm_rope<<<20,256,0,s>>>(q,k,qw,kw,g,pos_dev,off);}
}
