#include "insignia_deltanet.cuh"
#include <cuda_runtime.h>
#include <cmath>
#include <cstdio>
#include <vector>
#define OK(x) do{auto e=(x);if(e){printf("CUDA %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){constexpr int H=32,K=128,V=128,KH=16;std::vector<float>s(H*K*V),q(KH*K),k(KH*K),v(H*V),g(H),b(H),ref(H*V),out(H*V);for(size_t i=0;i<s.size();i++)s[i]=float(int(i*13%37)-18)*1e-3f;for(size_t i=0;i<q.size();i++){q[i]=float(int(i*7%29)-14)*.03f;k[i]=float(int(i*11%31)-15)*.02f;}for(size_t i=0;i<v.size();i++)v[i]=float(int(i*5%23)-11)*.04f;for(int h=0;h<H;h++){g[h]=-.01f*(1+h%7);b[h]=.1f+.02f*(h%11);int kh=h/2;float qn=1e-6f,kn=1e-6f;for(int i=0;i<K;i++){qn+=q[kh*K+i]*q[kh*K+i];kn+=k[kh*K+i]*k[kh*K+i];}qn=1.f/sqrtf(qn)/sqrtf(float(K));kn=1.f/sqrtf(kn);float d=expf(g[h]);for(int j=0;j<V;j++){float mem=0;for(int i=0;i<K;i++)mem+=s[(h*K+i)*V+j]*d*k[kh*K+i]*kn;float delta=(v[h*V+j]-mem)*b[h];float z=0;for(int i=0;i<K;i++){float&x=s[(h*K+i)*V+j];x=x*d+k[kh*K+i]*kn*delta;z+=x*q[kh*K+i]*qn;}ref[h*V+j]=z;}}
float *ds,*dq,*dk,*dv,*dg,*db,*dy;OK(cudaMalloc(&ds,s.size()*4));OK(cudaMalloc(&dq,q.size()*4));OK(cudaMalloc(&dk,k.size()*4));OK(cudaMalloc(&dv,v.size()*4));OK(cudaMalloc(&dg,g.size()*4));OK(cudaMalloc(&db,b.size()*4));OK(cudaMalloc(&dy,out.size()*4)); // state now contains CPU-updated state; reconstruct original deterministically
for(size_t i=0;i<s.size();i++)s[i]=float(int(i*13%37)-18)*1e-3f;OK(cudaMemcpy(ds,s.data(),s.size()*4,cudaMemcpyHostToDevice));OK(cudaMemcpy(dq,q.data(),q.size()*4,cudaMemcpyHostToDevice));OK(cudaMemcpy(dk,k.data(),k.size()*4,cudaMemcpyHostToDevice));OK(cudaMemcpy(dv,v.data(),v.size()*4,cudaMemcpyHostToDevice));OK(cudaMemcpy(dg,g.data(),g.size()*4,cudaMemcpyHostToDevice));OK(cudaMemcpy(db,b.data(),b.size()*4,cudaMemcpyHostToDevice));insignia::deltanet_decode(ds,dq,dk,dv,dg,db,dy);OK(cudaDeviceSynchronize());OK(cudaMemcpy(out.data(),dy,out.size()*4,cudaMemcpyDeviceToHost));float err=0,abs=0;for(size_t i=0;i<out.size();i++){abs=fmaxf(abs,fabsf(out[i]-ref[i]));err=fmaxf(err,fabsf(out[i]-ref[i])/(fabsf(ref[i])+1e-5f));}cudaEvent_t a,z;cudaEventCreate(&a);cudaEventCreate(&z);cudaEventRecord(a);for(int i=1000;i;i--)insignia::deltanet_decode(ds,dq,dk,dv,dg,db,dy);cudaEventRecord(z);cudaEventSynchronize(z);float ms;cudaEventElapsedTime(&ms,a,z);printf("DeltaNet decode max_abs=%g max_rel=%g %.3f ms/layer\n",abs,err,ms/1000);return err<3e-3f?0:1;}
